#!/usr/bin/env python3
"""Extract PDF text into PraxFlow raw Markdown with page traceability.

This helper intentionally does not perform OCR. Pages with little/no extractable
text are reported as OCR candidates so the agent can choose an OCR tool only
when needed.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Callable, Iterable


@dataclass
class PageResult:
    page: int
    method: str
    chars: int
    status: str
    notes: list[str]


def _extract_with_pymupdf(pdf: Path) -> list[str]:
    import fitz  # type: ignore

    doc = fitz.open(pdf)
    try:
        return [page.get_text("text") or "" for page in doc]
    finally:
        doc.close()


def _extract_with_pypdf(pdf: Path) -> list[str]:
    from pypdf import PdfReader  # type: ignore

    reader = PdfReader(str(pdf))
    return [(page.extract_text() or "") for page in reader.pages]


def choose_extractor() -> tuple[str, Callable[[Path], list[str]]]:
    try:
        import fitz  # noqa: F401

        return "pymupdf", _extract_with_pymupdf
    except Exception:
        pass

    try:
        import pypdf  # noqa: F401

        return "pypdf", _extract_with_pypdf
    except Exception as exc:
        raise RuntimeError(
            "No supported PDF extractor is installed. Install PyMuPDF "
            "(`python -m pip install pymupdf`) or pypdf "
            "(`python -m pip install pypdf`)."
        ) from exc


def normalize_text(text: str) -> str:
    # Preserve semantic content while normalizing only line endings/trailing space.
    lines = [line.rstrip() for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    return "\n".join(lines).strip()


def build_raw(pdf: Path, pages: Iterable[str]) -> tuple[str, list[PageResult]]:
    out: list[str] = [f"# Raw extraction: {pdf.name}", "", "> Generated by PraxFlow PDF ingestion. Treat this as evidence, not an implementation specification.", ""]
    results: list[PageResult] = []

    for index, original in enumerate(pages, start=1):
        text = normalize_text(original)
        notes: list[str] = []
        if len(text) < 20:
            status = "OCR_CANDIDATE"
            notes.append("Very little extractable text; inspect page image and consider OCR.")
        else:
            status = "EXTRACTED"

        results.append(PageResult(index, "text-layer", len(text), status, notes))
        out.extend(
            [
                "---",
                "",
                f"<!-- source_file: {pdf.name} -->",
                f"<!-- source_page: {index} -->",
                "",
                f"## Page {index}",
                "",
                text if text else "TODO_VERIFY: No reliable text extracted from this page. Inspect the source page; OCR may be required.",
                "",
            ]
        )

    return "\n".join(out).rstrip() + "\n", results


def build_report(pdf: Path, extractor_name: str, results: list[PageResult]) -> str:
    ocr_candidates = [r.page for r in results if r.status == "OCR_CANDIDATE"]
    failed = [r.page for r in results if r.status == "FAILED"]
    overall = "PASS"
    if failed:
        overall = "BLOCKED"
    elif ocr_candidates:
        overall = "PASS_WITH_WARNINGS"

    lines = [
        f"# Extraction report: {pdf.name}",
        "",
        f"- Extractor: `{extractor_name}`",
        f"- Total pages: {len(results)}",
        f"- OCR candidates: {len(ocr_candidates)}",
        f"- Failed pages: {len(failed)}",
        f"- Overall result: **{overall}**",
        "",
    ]

    if ocr_candidates:
        lines.extend(["## OCR candidates", "", ", ".join(map(str, ocr_candidates)), ""])

    lines.extend(["## Page details", "", "| Page | Method | Characters | Status | Notes |", "|---:|---|---:|---|---|"])
    for r in results:
        notes = "; ".join(r.notes).replace("|", "\\|")
        lines.append(f"| {r.page} | {r.method} | {r.chars} | {r.status} | {notes} |")

    lines.extend(
        [
            "",
            "## Next action",
            "",
            "Inspect every OCR candidate and any visually important tables/diagrams against the original PDF before treating this extraction as complete evidence.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Extract a PDF into PraxFlow raw Markdown.")
    parser.add_argument("pdf", type=Path)
    parser.add_argument("--out-dir", type=Path, default=Path("docs/raw"))
    parser.add_argument("--json", action="store_true", help="Print machine-readable result summary.")
    args = parser.parse_args()

    pdf = args.pdf
    if not pdf.is_file() or pdf.suffix.lower() != ".pdf":
        parser.error(f"Not a PDF file: {pdf}")

    try:
        extractor_name, extractor = choose_extractor()
        pages = extractor(pdf)
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    args.out_dir.mkdir(parents=True, exist_ok=True)
    raw, results = build_raw(pdf, pages)
    report = build_report(pdf, extractor_name, results)

    stem = pdf.stem
    raw_path = args.out_dir / f"{stem}_raw.md"
    report_path = args.out_dir / f"{stem}_extraction_report.md"
    raw_path.write_text(raw, encoding="utf-8")
    report_path.write_text(report, encoding="utf-8")

    summary = {
        "pdf": str(pdf),
        "extractor": extractor_name,
        "raw": str(raw_path),
        "report": str(report_path),
        "pages": len(results),
        "ocr_candidates": [r.page for r in results if r.status == "OCR_CANDIDATE"],
    }
    if args.json:
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    else:
        print(f"raw: {raw_path}")
        print(f"report: {report_path}")
        if summary["ocr_candidates"]:
            print("OCR candidates:", ", ".join(map(str, summary["ocr_candidates"])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
